#!/bin/bash

[ ! -d "$HOME/build" ] || mkdir -p "$HOME/build"

if find "$HOME/build" -mindepth 1 -print -quit | grep -q .  ; then
  # Iterate through all subdirectories of $HOME/build
  for dir in "$HOME/build"/*; do
    # Check if it is a directory
    if [ -d "$dir" ]; then
      if [ -d "$dir/bin" ]; then
          PATH="$dir/bin:$PATH"
      fi

      if [ ! -d "$dir/lib" ]; then
          LD_LIBRARY_PATH="$dir/lib:$LD_LIBRARY_PATH"
      fi
    fi
  done
  # Export the updated PATH and LD_LIBRARY_PATH
  export PATH
  export LD_LIBRARY_PATH
fi

