#! /bin/bash

DOTFILES_DIR=$HOME/dotfiles
GITHUB_REPO="git@github.com:LiuTaowen-Tony/dotfiles.git"

if [ $# -ne 1 ]; then 
  echo "please specify direction, u for upload, d for download"
  exit 2
fi

FILES=( .tmux.conf .gitconfig )
if [ -d "$HOME/.SpaceVim" ] ; then 
  FILES+=(".SpaceVim.d")
else
  FILES+=(".vimrc")
fi


cd ${DOTFILES_DIR}

if ! git pull > /dev/null; then 
  echo "sync_dotfiles : cannot pull from remote"
  exit 1
fi

if [ $1 == "u" ]; then
  for file in "${FILES[@]}"; do
    cp -r "$HOME/$file" $DOTFILES_DIR
  done
  git add . 
  git commit -m "update" 
  if ! git push; then 
    echo "sync_dotfiles : push failed, please resolve manually"
    exit 1
  fi
elif [ $1 == "d" ]; then
  for file in "${FILES[@]}"; do
    cp -r "$DOTFILES_DIR/$file" $HOME
  done
else 
  echo "sync_dotfiles : please specify direction, u for upload, d for download"
  exit 1
fi

